spring:
  datasource:
    url: jdbc:mysql://localhost:3306/journaldb
    username: root
    password: Itachi9368@
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect

  # To change port no
#server:
#  port: 8081
#  servlet:
#    context-path: /journal #ab localhost:8081/journal (mandatory)

weather:
  api:
    key: e24f8cb0ae2b5eb1200124a6ce37b1c7
